# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Real Life With the A'baums
title-aaron: Real Life with Mr. A'baum
title-alyssa: Real Life with Mrs. A'baum
tagline: Keepin' it real all day long
tagline-aaron: Husband + Father + Jack of Some Trades
tagline-alyssa: Jesus-Follower. Wife-y. No-Drama-Baby-Mama.
email: your-email@domain.com
description: We hope that you will be encouraged (or at least amused...) as we try to keep it real around here. We "A'baums" are a party of four living down yonder (ahem, the South...) who are just trying to live our lives for Jesus. We hope that you can see Him here and that you find Him in the midst of your own "real life."
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://reallifewiththeabaums.com" # the base hostname & protocol for your site
permalink: :year/:month/:day/:title/index.html

paginate: 3
paginate_path: "/page/:num/"

categories:
    generate_all: false
    pagination: 2
    directory: .
    details:
      aaron:
        layout: default-aaron.html
        category: aaron
      alyssa:
        layout: default-alyssa.html
        category: alyssa

# Build settings
markdown: kramdown
gems:
    - jekyll-paginate
    - octopress-autoprefixer
